### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by GiffenGood** [MohawkMEDIC/everest#10]
Hi,

Where do I find the the source for the assemblies located in the Solution Items folder?  

Thanks.

**Comment by nityan** [comment]
Hello,
The sources for the items in the Solution Items folder are not available for general use.
Thanks,
Nityan

**Comment by justin-fyfe** [comment]
Should clarify, the sources for the assemblies starting with MARC.Everest.RMIM.* contain code which was generated from HL7 MIF files and are thus Copyright (C) by HL7 International, and Canada Health Infoway. Distributing the source code is a legal gray area which is why we don't do this and why these are distributed in binary form only.

If needed for a source code audit, you can generate your own copy of the these assemblies (and thus the source files) from the source HL7 MIFs. The procedure is as follows:

1. Register for an HL7 International Account
2. Download the appropriate HL7 standard bundle (for example: NE2008, NE2010, etc.)
3. Run the GPMR tooling (the wizard or using the tool ```gpmr``` from the command line)
4. Compile the generated SLN file (or have the gpmr tool produce the DLL for you)
5. Use the newly compiled tool DLL in your solution
